input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 5; index++) {
        basic.clearScreen()
        basic.pause(100)
        led.plot(1, 1)
        basic.pause(100)
        led.plot(0, 3)
        basic.pause(100)
        led.plot(1, 4)
        basic.pause(100)
        led.plot(4, 3)
        basic.pause(100)
        led.plot(3, 4)
        basic.pause(100)
        led.plot(3, 1)
        basic.pause(100)
        led.plot(2, 4)
    }
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 5; index++) {
        basic.clearScreen()
        led.plot(0, 0)
        led.setBrightness(75)
        basic.pause(100)
        led.plot(0, 2)
        led.setBrightness(148)
        basic.pause(100)
        led.setBrightness(31)
        led.plot(2, 4)
        basic.pause(100)
        led.setBrightness(255)
        led.plot(4, 3)
        basic.pause(100)
        led.setBrightness(148)
        led.plot(2, 1)
        basic.pause(100)
        led.setBrightness(51)
        led.plot(4, 0)
        basic.pause(100)
        led.setBrightness(212)
        led.plot(0, 4)
    }
})
